monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: grouped
            excluded_http_codes: [404, 405, 403]
        grouped:
            type: group
            members: [deduplicated, stream]
        deduplicated:
            type: deduplication
            handler: swift_mailer
        swift_mailer:
            type: symfony_mailer
            from_email:   'contact@mitenygasy.com'
            to_email:     '%env(resolve:CRITICAL_MAIL_RECIPIENT)%'
            subject:      'CRITICAL MG : %%message%%'
            level:        debug
            formatter:    monolog.formatter.html
            content_type: text/html
        stream:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
